export const FETCH_ACTIVITY_START = 'FETCH_ACTIVITY_START'
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS'
export const FETCH_ACTIVITY_FAIL = 'FETCH_ACTIVITY_FAIL'

export const LOAD_SECTION_START = 'LOAD_SECTION_START'
export const LOAD_SECTION_SUCCESS = 'LOAD_SECTION_SUCCESS'
export const LOAD_SECTION_FAIL = 'LOAD_SECTION_FAIL'



